### ISSUE TITLE
dassl: CRITICAL: Renaming of RWORK file(s) failed. (renameIntermediateFiles())

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Java#251]
Hey,

i was trying to install RMG from scratch on my local ubuntu machine. everything goes smoothly: "make" assembles everything including dasslAUTO.EXE. Then i try to run the minimal example and it crashes (exit value "2") and logs:

`"CRITICAL: Renaming of RWORK file(s) failed. (renameIntermediateFiles())"`

The ODESolver folder contains the SolverInput.data file. The above message is thrown because RWORK and IWORK were not written (they can thus not be renamed neither).

The exception is thrown in JDASSL.java. In that piece of code it says that RWORK and IWORK might not necessarily be written out before the actual DAE solver step, but afterwards they should certainly be renamed...anyways, besides the absence of RWORK, and IWORK, SolverOutput.dat was not present neither.

Does anybody have a clue of what i am doing wrong here? might it be related to the platform (linux) where chmod's are necessary? (all executables were set to code 777)

**Comment by Alborzi** [comment]
Dear all,
I am using the latest RMG compiled form the source code on windows 7 and getting the same error. I tried to run the input file into dassl auto as RWest has suggested but the Dassl alone works and it creates IWORK_0.Dat and RWORK_0.Dat respectively.  
Any suggestion is much appreciated.
 Ehsan Alborzi

**Comment by DetlevCM** [comment]
Just throwing in another comment - fiddling with RMG again, I saw the error as well, for the first time only once on my desktop.

Does anybody here know if there is some kind of timeout involved?
I'm specculating, but it looks to me as if the desired event (file name change etc.) does not occur fast enough it fails.

**Comment by nickvandewiele** [comment]
I do not have extensive experience with compiling RMG on Windows (and certainly not with Win 7). Nevertheless, previous compilation issues on linux machines were related to the used compilers and versions. 

1) Did you compile the fortran source code on windows yourself, or did you copy the DASSL.exe executable from sourceforge? If compiled yourself, could you show how you did that? That way, I can figure out if I can reproduce it.

2) Could you elaborate on the compilers and versions that were used to compile the fortran code?

**Comment by DetlevCM** [comment]
Well, I was the tech support - so I think I can answer that:

On Windows one has two options, MinGW or TDM - I prefer TDM because it is easier for 64bit, however we need 32bit for RMG, but fine.
1) Install TDM (the bin folder must be in PATH) http://tdm-gcc.tdragon.net/
2) install a Java JDK and set JAVA_HOME to the root of the Java install - typically C:\Program Files\Java\jdk_xx_xx_xx
3) download the ant binaries, and add the bin to PATH http://ant.apache.org/bindownload.cgi
4) patch the "make.bat" - change g95 to gfortran

In a command line run make or run make.bat, then do "ant jar" to build the java executable, done.
This builds all executables from source.

Currently TDM GCC supplies GCC 4.9.2

The error occurs regularly on Ehsan's laptop on the Desktop - we tried copying over a compiled version from my desktop (it works on my desktop) which also failed on his laptop.
I was suspecting some form of file locking, BUT there is no reason why this should occur...
